=pod

=head1 Simple DirectMedia Library Bindings for Perl

=head2 Welcome

SDL Perl are a set of bindings to the Simple DirectMedia Library (SDL).

'Simple DirectMedia Layer is a cross-platform multimedia library designed to provide low level access to audio, keyboard, mouse, joystick, 
3D hardware via OpenGL, and 2D video framebuffer. It is used by MPEG playback software, emulators, and many popular games, including the 
award winning Linux port of "Civilization: Call To Power."' --L<www.libsdl.org>

SDL Perl is an active and exciting project with many facets. Explore this website to learn more. 

=head3 Getting Started

To begin using SDL Perl read the tutorials and documentation. 

=head3 Contribute

=over

=item IRC

Talk to us on channel L<#sdl|http://widget.mibbit.com/?settings=89f140215d60860684cee2f6a917607f&server=irc.perl.org&channel=%23sdl> .

=item Mailing List

Send us an email at L<mailing list| mailto:sdl-devel@perl.org>.

=item Testing and Development

Join us on the trac L<site| http://sdlperl.ath.cx/projects/SDLPerl> to get started on making and grabing tickets. 

To begin testing read L<this| http://sdlperl.ath.cx/projects/SDLPerl/wiki/Testing>.

=back

=head1 Latest News

=head2 July 01 2010

=head3 CPAN Release
	
L<SDL 2.5|http://search.cpan.org/~kthakore> RC is on CPAN! The new API has many changes and much more improvements. So check it out ;o)

SDL Perl at v2.2.6 on CPAN is the last of it's kind which will have the old API.

=head3 Active Development

SDL Perl is being actively developed to v3.0. The process is as below:

=head3 TODO

=over 4

=item *

Make SDL work with Frozen Bubble

Frozen Bubble is being reviewed as we speak! Until then

  cpan Games::FrozenBubble

=back

=cut 
